import type { Metadata } from "next";
import AboutUs from "../_components/about-us";

export const metadata: Metadata = {
    title: "Hello World",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
    openGraph: {
        type: "article",
        title: "Milan"
    },
  };

const AboutPage = () => {
    return <div className="mt-16">
        <AboutUs />
    </div>
}

export default AboutPage