import type { Metadata } from "next";
import ContactUs from "../_components/contact-us";

export const metadata: Metadata = {
    title: "Hello World",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
    openGraph: {
        type: "article",
        title: "Milan"
    },
  };

const ContactPage = () => {
    return <div className="mt-16">
        <ContactUs />
    </div>
}

export default ContactPage